name: 使用pushplus推送通知

on:
  workflow_dispatch:
  # push:
  schedule:
    - cron: '30 6 * * 1-5'

jobs:
  send_msg:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 设置py3
        uses: actions/setup-python@v1
        with:
          python-version: '3.8.7'
      - name: pip安装依赖
        run: python -m pip install requests
      - name: 发送通知
        env:
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
        run: python pushplus.py
